In [1]:
# this is a list we cant do vectors operation on it 
a=[1,5,4,8,9,9,5,5]
print(a)

[1, 5, 4, 8, 9, 9, 5, 5]


In [2]:
# b=a+2
b=a+[2]
print(b)

[1, 5, 4, 8, 9, 9, 5, 5, 2]


In [3]:
import numpy as np

In [4]:
# np.array convert it into a vector now we can perform vector operations on it. 

b=np.array(a)
print(b)
# this is a one diminsional array 
print(np.shape(b))
# it will add 2 to all elements 
print(b+2)

[1 5 4 8 9 9 5 5]
(8,)
[ 3  7  6 10 11 11  7  7]


In [5]:
# now same operation we did in first neuron with for loop we will do it with vector lot ease and efficient way 
inputs=np.array([.5,.3,.2])
weights=np.array([.4,.7,.2])
print(np.shape(inputs))
output=np.dot(inputs,weights)
print(output)
sig_activ=1/(1+np.exp(-output))
print(sig_activ)

(3,)
0.45000000000000007
0.610639233949222


In [6]:
a=np.array([[1,5],[7,8]])
print(a)
print(np.shape(a))
# now this is like a matrix 
# it we want to read 3rd element of 1st row 
print(a[1,1])
c=a[1:,1:]
print(c)
b=np.reshape(a,(4,1))
d=b.T
print(b)
print(d)

[[1 5]
 [7 8]]
(2, 2)
8
[[8]]
[[1]
 [5]
 [7]
 [8]]
[[1 5 7 8]]


In [7]:
a=np.array([[1,5,7,8]])

In [8]:
# give us random values of given size 
a=np.random.rand(3,4)
print(a)
# give us random values of given size and round it to decimal
a=np.round(np.random.rand(3,4),2)
print(a)

# give us random values of integers from range of 0 to 10, size 4 row 5 col
a=np.random.randint(0,10,size=(4,5))

print(a)

[[0.66148531 0.92202063 0.75854531 0.70206063]
 [0.37648297 0.20703975 0.67311591 0.90789935]
 [0.97612682 0.06653044 0.21873002 0.29152479]]
[[0.48 0.9  0.   0.81]
 [0.13 0.43 0.47 0.56]
 [0.9  0.34 0.31 0.13]]
[[2 0 6 1 2]
 [1 3 3 7 6]
 [2 0 5 7 8]
 [7 1 4 2 7]]


In [9]:
a=np.zeros((5,2),dtype=bool)
print(a)

a=np.zeros(20)
print(a)

a=np.zeros(20, dtype=int)
print(a)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [10]:


a = np.array([9, 5, 7, 4])
c = np.array([9, 5, 4, 3])

print(np.shape(a))
print(type(a))
print(np.shape(c))
print(np.dot(a, c))

# using matmul we are doing matrix multiplication 
print(np.matmul(a.T, c))

a=np.round(np.random.rand(3,4),2)
print(type(a))
b=np.round(np.random.rand(3,4),2)

print(np.dot(a.T,b))
print(np.matmul(a.T,b))

a = np.random.rand(3,4,2)
print(a)





(4,)
<class 'numpy.ndarray'>
(4,)
146
146
<class 'numpy.ndarray'>
[[0.3389 0.58   0.4226 0.4195]
 [0.1308 0.2958 0.1889 0.1806]
 [0.4049 0.39   0.3701 0.3315]
 [0.4706 0.8424 0.539  0.3798]]
[[0.3389 0.58   0.4226 0.4195]
 [0.1308 0.2958 0.1889 0.1806]
 [0.4049 0.39   0.3701 0.3315]
 [0.4706 0.8424 0.539  0.3798]]
[[[0.87250496 0.47666299]
  [0.62663897 0.55481996]
  [0.65959434 0.54532179]
  [0.59554723 0.82876965]]

 [[0.40047569 0.94208765]
  [0.80384111 0.13789255]
  [0.84653224 0.16832633]
  [0.38205145 0.95713581]]

 [[0.46785855 0.46170597]
  [0.63958023 0.06141978]
  [0.42564361 0.43399389]
  [0.51030642 0.99403909]]]
