In [1]:
# this is a list we cant do vectors operation on it 
a=[1,5,4,8,9,9,5,5]
print(a)

[1, 5, 4, 8, 9, 9, 5, 5]


In [2]:
# b=a+2
b=a+[2]
print(b)

[1, 5, 4, 8, 9, 9, 5, 5, 2]


In [3]:
import numpy as np

In [4]:
# np.array convert it into a vector now we can perform vector operations on it. 

b=np.array(a)
print(b)
# this is a one diminsional array 
print(np.shape(b))
# it will add 2 to all elements 
print(b+2)

[1 5 4 8 9 9 5 5]
(8,)
[ 3  7  6 10 11 11  7  7]


In [5]:
# now same operation we did in first neuron with for loop we will do it with vector lot ease and efficient way 
inputs=np.array([.5,.3,.2])
weights=np.array([.4,.7,.2])
print(np.shape(inputs))
output=np.dot(inputs,weights)
print(output)
sig_activ=1/(1+np.exp(-output))
print(sig_activ)

(3,)
0.45000000000000007
0.610639233949222


In [6]:
a=np.array([[1,5],[7,8]])
print(a)
print(np.shape(a))
# now this is like a matrix 
# it we want to read 3rd element of 1st row 
print(a[1,1])
c=a[1:,1:]
print(c)
b=np.reshape(a,(4,1))
d=b.T
print(b)
print(d)

[[1 5]
 [7 8]]
(2, 2)
8
[[8]]
[[1]
 [5]
 [7]
 [8]]
[[1 5 7 8]]


In [7]:
a=np.array([[1,5,7,8]])

In [8]:
# give us random values of given size 
a=np.random.rand(3,4)
print(a)
# give us random values of given size and round it to decimal
a=np.round(np.random.rand(3,4),2)
print(a)

# give us random values of integers from range of 0 to 10, size 4 row 5 col
a=np.random.randint(0,10,size=(4,5))

print(a)

[[0.37961832 0.20980901 0.13609506 0.70533684]
 [0.36506259 0.74390967 0.30334938 0.60483151]
 [0.89223411 0.46966447 0.31761375 0.10004341]]
[[0.66 0.27 0.94 0.34]
 [0.61 0.89 0.16 0.55]
 [0.81 0.32 0.09 0.36]]
[[3 2 5 5 1]
 [1 0 5 6 8]
 [9 1 2 3 0]
 [3 9 4 5 0]]


In [9]:
a=np.zeros((5,2),dtype=bool)
print(a)

a=np.zeros(20)
print(a)

a=np.zeros(20, dtype=int)
print(a)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [10]:


a = np.array([9, 5, 7, 4])
c = np.array([9, 5, 4, 3])

print(np.shape(a))
print(type(a))
print(np.shape(c))
print(np.dot(a, c))

# using matmul we are doing matrix multiplication 
print(np.matmul(a.T, c))

a=np.round(np.random.rand(3,4),2)
print(type(a))
b=np.round(np.random.rand(3,4),2)

print(np.dot(a.T,b))
print(np.matmul(a.T,b))

a = np.random.rand(3,4,2)
print(a)





(4,)
<class 'numpy.ndarray'>
(4,)
146
146
<class 'numpy.ndarray'>
[[0.6789 0.6603 0.3303 0.5373]
 [0.4122 0.5406 0.2228 0.3256]
 [0.4484 0.31   0.2374 0.3962]
 [0.1685 0.4883 0.4091 0.4173]]
[[0.6789 0.6603 0.3303 0.5373]
 [0.4122 0.5406 0.2228 0.3256]
 [0.4484 0.31   0.2374 0.3962]
 [0.1685 0.4883 0.4091 0.4173]]
[[[0.34139932 0.18976045]
  [0.30424356 0.74789986]
  [0.13692214 0.98480236]
  [0.14804174 0.30300372]]

 [[0.23952197 0.85368452]
  [0.20962363 0.69861761]
  [0.24544654 0.17563865]
  [0.84049902 0.86793148]]

 [[0.16883556 0.83535382]
  [0.17789231 0.89036015]
  [0.09925107 0.24474003]
  [0.59860501 0.30409695]]]


In [21]:
a=np.linspace(0,50,num=51)
b=np.zeros(51)

c=a[::2]
d=a[1::2]
print(c)
print(d)

e=np.zeros(np.shape(a))
e[::2]=c
e[1::2]=d

print(e)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50.]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
