In [5]:
# this is a list we cant do vectors operation on it 
a=[1,5,4,8,9,9,5,5]
print(a)

[1, 5, 4, 8, 9, 9, 5, 5]


In [10]:
# b=a+2
b=a+[2]
print(b)

TypeError: can only concatenate list (not "int") to list

In [2]:
import numpy as np

In [13]:
# np.array convert it into a vector now we can perform vector operations on it. 

b=np.array(a)
print(b)
# this is a one diminsional array 
print(np.shape(b))
# it will add 2 to all elements 
print(b+2)

[1 5 4 8 9 9 5 5]
(8,)
[ 3  7  6 10 11 11  7  7]


In [22]:
# now same operation we did in first neuron with for loop we will do it with vector lot ease and efficient way 
inputs=np.array([.5,.3,.2])
weights=np.array([.4,.7,.2])
print(np.shape(inputs))
output=np.dot(inputs,weights)
print(output)
sig_activ=1/(1+np.exp(-output))
print(sig_activ)

(3,)
0.45000000000000007
0.610639233949222


In [35]:
a=np.array([[1,5],[7,8]])
print(a)
print(np.shape(a))
# now this is like a matrix 
# it we want to read 3rd element of 1st row 
print(a[1,1])
c=a[1:,1:]
print(c)
b=np.reshape(a,(4,1))
d=b.T
print(b)
print(d)

[[1 5]
 [7 8]]
(2, 2)
8
[[8]]
[[1]
 [5]
 [7]
 [8]]
[[1 5 7 8]]


In [3]:
a=np.array([[1,5,7,8]])