In [1]:
# this is a list we cant do vectors operation on it 
a=[1,5,4,8,9,9,5,5]
print(a)

[1, 5, 4, 8, 9, 9, 5, 5]


In [2]:
# b=a+2
b=a+[2]

print(b)

[1, 5, 4, 8, 9, 9, 5, 5, 2]


In [3]:
import numpy as np

In [4]:
# np.array convert it into a vector now we can perform vector operations on it. 

b=np.array(a)
print(b)
# this is a one diminsional array 
print(np.shape(b))
# it will add 2 to all elements 
print(b+2)

[1 5 4 8 9 9 5 5]
(8,)
[ 3  7  6 10 11 11  7  7]


In [5]:
# now same operation we did in first neuron with for loop we will do it with vector lot ease and efficient way 
inputs=np.array([.5,.3,.2])
weights=np.array([.4,.7,.2])
print(np.shape(inputs))
output=np.dot(inputs,weights)
print(output)
sig_activ=1/(1+np.exp(-output))
print(sig_activ)

(3,)
0.45000000000000007
0.610639233949222


In [6]:
a=np.array([[1,5],[7,8]])
print(a)
print(np.shape(a))
# now this is like a matrix 
# it we want to read 3rd element of 1st row 
print(a[1,1])
c=a[1:,1:]
print(c)
b=np.reshape(a,(4,1))
d=b.T
print(b)
print(d)

[[1 5]
 [7 8]]
(2, 2)
8
[[8]]
[[1]
 [5]
 [7]
 [8]]
[[1 5 7 8]]


In [7]:
a=np.array([[1,5,7,8]])

In [8]:
# give us random values of given size 
a=np.random.rand(3,4)
print(a)
# give us random values of given size and round it to decimal
a=np.round(np.random.rand(3,4),2)
print(a)

# give us random values of integers from range of 0 to 10, size 4 row 5 col
a=np.random.randint(0,10,size=(4,5))

print(a)

[[0.02503658 0.14286111 0.80496073 0.01395331]
 [0.71534124 0.02770233 0.60652134 0.83416502]
 [0.34728556 0.63264344 0.56069236 0.55888208]]
[[0.53 0.07 0.71 0.69]
 [0.38 0.66 0.16 0.04]
 [0.68 0.42 0.36 0.55]]
[[7 4 2 8 7]
 [0 2 0 4 6]
 [9 2 8 6 0]
 [8 7 9 2 0]]


In [9]:
a=np.zeros((5,2),dtype=bool)
print(a)

a=np.zeros(20)
print(a)

a=np.zeros(20, dtype=int)
print(a)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [10]:


a = np.array([9, 5, 7, 4])
c = np.array([9, 5, 4, 3])

print(np.shape(a))
print(type(a))
print(np.shape(c))
print(np.dot(a, c))

# using matmul we are doing matrix multiplication 
print(np.matmul(a.T, c))

a=np.round(np.random.rand(3,4),2)
print(type(a))
b=np.round(np.random.rand(3,4),2)

print(np.dot(a.T,b))
print(np.matmul(a.T,b))

a = np.random.rand(3,4,2)
print(a)





(4,)
<class 'numpy.ndarray'>
(4,)
146
146
<class 'numpy.ndarray'>
[[0.7299 0.7819 0.2603 1.1543]
 [0.9625 0.8173 0.5648 0.6713]
 [0.6939 0.5719 0.1029 0.7363]
 [1.5086 1.312  0.3696 1.6576]]
[[0.7299 0.7819 0.2603 1.1543]
 [0.9625 0.8173 0.5648 0.6713]
 [0.6939 0.5719 0.1029 0.7363]
 [1.5086 1.312  0.3696 1.6576]]
[[[0.2242302  0.67648835]
  [0.28900462 0.57579217]
  [0.99302347 0.72548913]
  [0.88496892 0.56978818]]

 [[0.64944478 0.81344174]
  [0.2015431  0.7096145 ]
  [0.69331815 0.94213354]
  [0.51888525 0.58209523]]

 [[0.56145175 0.16206693]
  [0.15858899 0.07329705]
  [0.67459532 0.69889984]
  [0.890979   0.68784999]]]


In [11]:
a=np.linspace(0,50,num=51)
b=np.zeros(51)

c=a[::2]
d=a[1::2]
print(c)
print(d)

e=np.zeros(np.shape(a))
e[::2]=c
e[1::2]=d

print(e)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50.]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [19]:
a=np.array([5,8,3,7,5,4,5,8,8,5])
for i in a:
    print(i)

5
8
3
7
5
4
5
8
8
5


In [22]:
a=np.array([5,8,3,7,5,4,5,8,8,5])
for idx,v in np.ndenumerate(a):
    print(idx,v)


(0,) 5
(1,) 8
(2,) 3
(3,) 7
(4,) 5
(5,) 4
(6,) 5
(7,) 8
(8,) 8
(9,) 5


In [23]:
a=np.array([[5,8,3],[5,7,6]])
for idx,v in np.ndenumerate(a):
    print(idx,v)

(0, 0) 5
(0, 1) 8
(0, 2) 3
(1, 0) 5
(1, 1) 7
(1, 2) 6


In [26]:
a=np.array([[5,8,3],[5,7,6]])
for v in a:
    print(v)

[5 8 3]
[5 7 6]


In [27]:
a=np.array([[5,8,3],[5,7,6]])
for r in a:
    for v in r:
        print(v)

5
8
3
5
7
6


In [28]:
a=np.array([[5,8,3],[5,7,6]])
for v in a.flatten():
    print(v)

5
8
3
5
7
6
